### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by JhonnyBn** [biga-ahk/biga.ahk#3]
I was reading AHK forums when I saw your [post](https://www.autohotkey.com/boards/viewtopic.php?p=308171&sid=3630adc6d2060600578f1505518acb16#p308171) and decided to look into big A. It seems a very nice thing to have in big/advanced scripts (because I like javascript and this seems like js)

Sorry for the awkward question but, what is this lib? After reading the first paragraphs of Quick Start, Getting Started and the repo's description I still do not understand what this lib does.

Also, there is a duplicate "Set this to" in the [attributes page](https://biga-ahk.github.io/biga.ahk/#/?id=quick-start):
A.limit := -1 Determines the number of times strings will be replaced when using [.replace](https://biga-ahk.github.io/biga.ahk/#/?id=replace) with a string argument. `Set this to Set this to` 1 to get closer to a javascript experience.

**Comment by Chunjee** [comment]
Hello,

This package is for anything and everything 👍 It includes useful utility methods for working with arrays, strings, etc. Because ahk's object doesn't have a lot of features out of the box; you may find biga.ahk most immediately useful for working with arrays or matrix tables (usually called object arrays on the forums)

Take this matrix table for example:
```autohotkey
users := [{"name":"Bill", "favoriteColor":"blue"}
	, {"name":"Ted", "favoriteColor":"red"}
	, {"name":"Socrates", "favoriteColor":"blue"}]
```
If one wanted to find everyone who has the favorite color blue; you would have write a loop and if statements. biga.ahk can do it in one line using it's `.filter` method:
```autohotkey
favoriteColorBlueArray := A.filter(users, {"favoriteColor":"blue"})
; => [{"favoriteColor": "blue", "name": "Bill"}, {"favoriteColor": "blue", "name": "Socrates"}]
```

If you need more inspiration please check out the [./examples](https://github.com/biga-ahk/biga.ahk/tree/master/examples) directory

**Comment by Chunjee** [comment]
Fixed docs with https://github.com/biga-ahk/biga.ahk/commit/91798b94222f975abc20d18597009039d0afcfa4
